export const palettes = {
  palette1: {
    id: "palette1",
    name: "Palette 1",
    preview: ["#102C57", "#DAC0A3", "#F8F0E5"],
    colors: {
      "--theme-primary": "#102C57",
      "--theme-secondary": "#DAC0A3",
      "--theme-button": "#102C57",
      "--theme-background": "#F8F0E5",
      "--theme-button-hover": "#DAC0A3",
      "--theme-card": "#FFFFFF",
      "--theme-icon-bg": "#102C57",
      "--theme-secondary-text": "#6B7280",
      "--theme-icon-color": "#FFFFFF",
      "--theme-primary-text": "#1A1A1A",
      "--theme-icon-bg-hover": "#DAC0A3",
      "--theme-icon-hover": "#FFFFFF",
    },
  },

  palette2: {
    id: "palette2",
    name: "Palette 2",
    preview: ["#27374D", "#526D82", "#DDE6ED"],
    colors: {
      "--theme-primary": "#27374D",
      "--theme-secondary": "#526D82",
      "--theme-button": "#27374D",
      "--theme-background": "#DDE6ED",
      "--theme-button-hover": "#9DB2BF",
      "--theme-card": "#FFFFFF",
      "--theme-icon-bg": "#27374D",
      "--theme-secondary-text": "#526D82",
      "--theme-icon-color": "#526D82",
      "--theme-primary-text": "#1A1A1A",
      "--theme-icon-bg-hover": "#526D82",
      "--theme-icon-hover": "#526D82",
    },
  },

  palette3: {
    id: "palette3",
    name: "Palette 3",
    preview: ["#840D0D", "#EAEAEA", "#F8F9FA"],
    colors: {
      "--theme-primary": "#840D0D",
      "--theme-secondary": "#EAEAEA",
      "--theme-button": "#840D0D",
      "--theme-background": "#F8F9FA",
      "--theme-button-hover": "#262626",
      "--theme-card": "#FFFFFF",
      "--theme-icon-bg": "#840D0D",
      "--theme-secondary-text": "#6B6B6B",
      "--theme-icon-color": "#FFFFFF",
      "--theme-primary-text": "#262626",
      "--theme-icon-bg-hover": "#262626",
      "--theme-icon-hover": "#FFFFFF",
    },
  },

  palette4: {
    id: "palette4",
    name: "Palette 4",
    preview: ["#000000", "#412D15", "#F7F5EF"],
    colors: {
      "--theme-primary": "#000000",
      "--theme-secondary": "#1F150C",
      "--theme-button": "#412D15",
      "--theme-background": "#F7F5EF",
      "--theme-button-hover": "#1F150C",
      "--theme-card": "#FFFFFF",
      "--theme-icon-bg": "#E1DCC9",
      "--theme-secondary-text": "#412D15",
      "--theme-icon-color": "#412D15",
      "--theme-primary-text": "#000000",
      "--theme-icon-bg-hover": "#412D15",
      "--theme-icon-hover": "#E1DCC9",
    },
  },

  palette5: {
    id: "palette5",
    name: "Palette 5",
    preview: ["#627254", "#76885B", "#F8F9F6"],
    colors: {
      "--theme-primary": "#627254",
      "--theme-secondary": "#76885B",
      "--theme-button": "#627254",
      "--theme-background": "#F8F9F6",
      "--theme-button-hover": "#76885B",
      "--theme-card": "#F1F3ED",
      "--theme-icon-bg": "#627254",
      "--theme-secondary-text": "#76885B",
      "--theme-icon-color": "#E1DCC9",
      "--theme-primary-text": "#2F2F2F",
      "--theme-icon-bg-hover": "#E1DCC9",
      "--theme-icon-hover": "#627254",
    },
  },

  palette6: {
    id: "palette6",
    name: "Palette 6",
    preview: ["#2F5755", "#5A9690", "#E0D9D9"],
    colors: {
      "--theme-primary": "#2F5755",
      "--theme-secondary": "#5A9690",
      "--theme-button": "#2F5755",
      "--theme-background": "#E0D9D9",
      "--theme-button-hover": "#432323",
      "--theme-card": "#FFFFFF",
      "--theme-icon-bg": "#2F5755",
      "--theme-secondary-text": "#2F5755",
      "--theme-icon-color": "#E0D9D9",
      "--theme-primary-text": "#432323",
      "--theme-icon-bg-hover": "#E0D9D9",
      "--theme-icon-hover": "#2F5755",
    },
  },
};